#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

host = data.get('host')

APP_URL = f"https://{host}"
APP_DEBUG = data.get("APP_DEBUG", "false")
REQUIRE_HTTPS = data.get("REQUIRE_HTTPS", "true")
PHANTOMJS_PDF_GENERATION = data.get("PHANTOMJS_PDF_GENERATION", "false")
PDF_GENERATOR = data.get("PDF_GENERATOR", "snappdf")
TRUSTED_PROXIES = data.get("TRUSTED_PROXIES", "*")
IN_USER_EMAIL= data.get("IN_USER_EMAIL", "admin@gmail.com")
IN_PASSWORD = data.get("IN_PASSWORD", "admin")
# MAIL_MAILER=log
# MAIL_HOST=smtp.mailtrap.io
# MAIL_PORT=2525
# MAIL_USERNAME=null
# MAIL_PASSWORD=null
# MAIL_ENCRYPTION=null
# MAIL_FROM_ADDRESS='user@example.com'
# MAIL_FROM_NAME='Self Hosted User'
# Mail
SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']
SMTP_ENCRYPTION = smtp_settings['encrypt_smtp']
SMTP_TLSVERIFY = smtp_settings['tls_verify']

invoice_config = {
    "APP_URL": APP_URL,
    "APP_DEBUG": APP_DEBUG,
    "REQUIRE_HTTPS": REQUIRE_HTTPS,
    "PHANTOMJS_PDF_GENERATION": PHANTOMJS_PDF_GENERATION,
    "PDF_GENERATOR": PDF_GENERATOR,
    "TRUSTED_PROXIES": TRUSTED_PROXIES,
    "IN_USER_EMAIL": IN_USER_EMAIL,
    "IN_PASSWORD": IN_PASSWORD,
    "MAIL_MAILER": "log",
    "MAIL_HOST": SMTP_HOST,
    "MAIL_PORT": SMTP_PORT,
    "MAIL_USERNAME": SMTP_USERNAME,
    "MAIL_PASSWORD": SMTP_PASSWORD,
    "MAIL_ENCRYPTION": SMTP_ENCRYPTION,
    "MAIL_FROM_ADDRESS": SMTP_USERNAME,
    "MAIL_FROM_NAME": SMTP_USERNAME,
}

agent.write_envfile("invoice.env", invoice_config)

#agent.dump_env()
